### ISSUE TITLE
About P(r|c)

### ISSUE THREAD

**Issue by LHRYANG** [hengyicai/ContrastiveLearning4Dialogue#5]
Hi, I have the below question:
target_scores, *_ = target_model_output
ref_scores, *_ = ref_model_output

If I do not make a mistake, the target/ref_scores are regarded as the probability, So I want to know how they are obtained and how to back propagation.

thanks a lot!

**Comment by hengyicai** [comment]
===>>"How they are obtained".
Both the `target_scores` and the `ref_scores` can be computed by the agent's function `compute_loss(batch)`. The `agent` here is a ParlAI agent, for example, the transformer agent or seq2seq agent. You can check `parlai/agents/contrastive_learning/seq2seq.py` for implementation details regarding its `compute_loss` function.

===>>"how to back propagation".
Once the function `compute_cl_loss()` returned the loss variable `cl_loss`, we can conduct back propagation to compute the gradients by `self.backward(cl_loss)`, as implemented in function `cl_train_step()` of `parlai/agents/contrastive_learning/common_things.py`.
