### ISSUE TITLE
Missing embedding, vocab and MSN model.

### ISSUE THREAD

**Issue by mattc95** [hengyicai/ContrastiveLearning4Dialogue#6]
I am preprocessing my own dataset, but I don't know where to get the word embedding, vocab, and MSN model as shown below.

https://github.com/hengyicai/ContrastiveLearning4Dialogue/blob/a3e2c1fc04e85231b33c65abec2a87a05cb06494/projects/contrastive_learning/scripts/compute_score.py#L75-L77

I have read the Github below to find the word embedding and MSN model I need.

https://github.com/MarkWuNLP/MultiTurnResponseSelection
https://github.com/twoflypig/MultiTurnResponseSelection

However, I think the one they provided is slightly different from what I want.

Could you provide the ones you used or give me some hints?

Thanks!

**Comment by hengyicai** [comment]
Hi, you can use the original MSN codebase (see [https://github.com/chunyuanY](https://github.com/chunyuanY)) to build the matching model using your own dataset. The embedding and vocab files you mentioned above are required by the original MSN codebase to conduct model training and inference. For the embedding and vocab file, as well as the training data for MSN model, you can build your own dataset into the right format using `projects/contrastive_learning/retrieval_models/MSN/create_training_data.py`, in which you need to provide your `train/valid/test` data and a pre-trained embedding file. This script will dump the training data into the right format required by the MSN codebase, including `{train, dev, test}.pkl` and `vocab_and_embeddings.pkl`. You can then use these data to train the MSN model. The `args.vocab_embed_path` refers to `vocab_and_embeddings.pkl` and `args. msn_model ` refers to the trained MSN model (e.g., model.pt).
